### ISSUE TITLE
Refactoring: Make class names unique

### ISSUE THREAD

**Issue by rubenthoms** [equinor/flow-diagram-explorer#21]
Currently, the class names are in the `FlowDiagramExplorer` namespace. However, this could lead to issues when the same class names are used other places in the same app. Apply a new naming scheme that uses the component's name and underscores, e.g. `FlowDiagramExplorer__className`.

**Comment by jorgenherje** [comment]
Closed by PR https://github.com/equinor/flow-diagram-explorer/pull/25
